---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rest-hello
    spec:
      containers:
        - image: registry.gitlab.com/petrelevich/dockerregistry/rest-hello:v2
          name: rest-hello
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
